# Generated by Django 2.1.7 on 2019-03-28 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('udated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=None, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
