# Generated by Django 2.1.7 on 2019-04-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190403_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='udated',
            new_name='updated',
        ),
    ]
